SRCS := ../common/init.S main.c dot.s
APP  := vec
CCFLAGS = -march=rv32imvac_zicsr_zifencei_zba_zbb_zbkb_zbs -O3
AFLAGS = -march=rv32imvac_zicsr_zifencei_zba_zbb_zbkb_zbs

include ../common/src_only_app.mk
