SRCS := ../../common/init.S main.c
APP  := sub
CCFLAGS = -march=rv32imac_zicsr_zifencei_zba_zbb_zbkb_zbs -O3
AFLAGS = -march=rv32imac_zicsr_zifencei_zba_zbb_zbkb_zbs

include ../../common/src_only_app.mk
