SRCS := ../common/init.S main.c
APP  := mandel
CCFLAGS = -march=rv32imvac_zicsr_zifencei_zba_zbb_zbkb_zbs -Os
AFLAGS = -march=rv32imvac_zicsr_zifencei_zba_zbb_zbkb_zbs

include ../common/src_only_app.mk
