SRCS := ../common/init.S main.c mem.s
APP  := mem
CCFLAGS = -march=rv32imvac_zicsr_zifencei_zba_zbb_zbkb_zbs -O0
AFLAGS = -march=rv32imvac_zicsr_zifencei_zba_zbb_zbkb_zbs

include ../common/src_only_app.mk
